name: black_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  #animated_splash_screen: ^1.3.0
  #page_transition: ^2.1.0
  tbib_splash_screen: ^1.0.0
  window_manager: ^0.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/draw.png
    - assets/images/black_box_1.png
    - assets/images/black_box_2.png
    - assets/images/sc_assault.jpg
    - assets/images/cod.jpg
    - assets/images/job_starting.png
    - assets/images/background.jpg